name: build/python

on:
  push:
    tags: "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Set up Python.
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install dependencies.
        run: |
          pip install pyquery

      - name: Run unit tests.
        run: |
          python -m unittest
        working-directory: ./python

      - name: Install build tools and generate distribution archives.
        run: |
          pip install setuptools wheel
          python setup.py sdist bdist_wheel
        working-directory: ./python

      - name: Publish a Python distribution to PyPI.
        uses: pypa/gh-action-pypi-publish@master
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          user: __token__
          # Config for secret: pypi_password.
          password: ${{ secrets.pypi_password }}
          packages_dir: ./python/dist
