name: build/dotnet

on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository.
        uses: actions/checkout@v1

      - name: Set up dotnet CLI.
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.302

      - name: Run unit tests.
        run: |
          dotnet test --logger "console;verbosity=detailed" RnzNewsTest
        working-directory: ./dotnet

      - name: Publish a NuGet package.
        uses: rohith/publish-nuget@v2
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          PROJECT_FILE_PATH: dotnet/RnzNews.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          TAG_COMMIT: false
          VERSION_STATIC: github.ref.replace(/^refs\/tags\/v/, '')
