name: build/dotnet

on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository.
        uses: actions/checkout@v1

      - name: Set up dotnet CLI.
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.302

      - name: Run unit tests.
        run: |
          dotnet test --logger "console;verbosity=detailed" RnzNewsTest
        working-directory: ./dotnet

      - name: Build a NuGet package.
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          dotnet pack -p:PackageVersion=${GITHUB_REF#refs/tags/v/}
        working-directory: ./dotnet

      - name: Publish the NuGet packge.
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          dotnet nuget push ./bin/Debug/RnzNews.*.nupkg \
            --api-key ${API_KEY} \
            --source https://api.nuget.org/v3/index.json
        env:
          API_KEY: ${{secrets.NUGET_API_KEY}}
